package SimpleType



type CodAddTransportationChargeBasisType string

const (
	CodAddTransportationChargeBasisTypeCOD_SURCHARGE CodAddTransportationChargeBasisType = "COD_SURCHARGE"

	CodAddTransportationChargeBasisTypeNET_CHARGE CodAddTransportationChargeBasisType = "NET_CHARGE"

	CodAddTransportationChargeBasisTypeNET_FREIGHT CodAddTransportationChargeBasisType = "NET_FREIGHT"

	CodAddTransportationChargeBasisTypeTOTAL_CUSTOMER_CHARGE CodAddTransportationChargeBasisType = "TOTAL_CUSTOMER_CHARGE"
)