package SimpleType


type DestinationControlStatementType string

const (
	DestinationControlStatementTypeDEPARTMENT_OF_COMMERCE DestinationControlStatementType = "DEPARTMENT_OF_COMMERCE"

	DestinationControlStatementTypeDEPARTMENT_OF_STATE DestinationControlStatementType = "DEPARTMENT_OF_STATE"
)