package SimpleType


type EdtTaxType string

const (
	EdtTaxTypeADDITIONAL_TAXES EdtTaxType = "ADDITIONAL_TAXES"

	EdtTaxTypeCONSULAR_INVOICE_FEE EdtTaxType = "CONSULAR_INVOICE_FEE"

	EdtTaxTypeCUSTOMS_SURCHARGES EdtTaxType = "CUSTOMS_SURCHARGES"

	EdtTaxTypeDUTY EdtTaxType = "DUTY"

	EdtTaxTypeEXCISE_TAX EdtTaxType = "EXCISE_TAX"

	EdtTaxTypeFOREIGN_EXCHANGE_TAX EdtTaxType = "FOREIGN_EXCHANGE_TAX"

	EdtTaxTypeGENERAL_SALES_TAX EdtTaxType = "GENERAL_SALES_TAX"

	EdtTaxTypeIMPORT_LICENSE_FEE EdtTaxType = "IMPORT_LICENSE_FEE"

	EdtTaxTypeINTERNAL_ADDITIONAL_TAXES EdtTaxType = "INTERNAL_ADDITIONAL_TAXES"

	EdtTaxTypeINTERNAL_SENSITIVE_PRODUCTS_TAX EdtTaxType = "INTERNAL_SENSITIVE_PRODUCTS_TAX"

	EdtTaxTypeOTHER EdtTaxType = "OTHER"

	EdtTaxTypeSENSITIVE_PRODUCTS_TAX EdtTaxType = "SENSITIVE_PRODUCTS_TAX"

	EdtTaxTypeSTAMP_TAX EdtTaxType = "STAMP_TAX"

	EdtTaxTypeSTATISTICAL_TAX EdtTaxType = "STATISTICAL_TAX"

	EdtTaxTypeTRANSPORT_FACILITIES_TAX EdtTaxType = "TRANSPORT_FACILITIES_TAX"
)