package SimpleType

type NetExplosiveClassificationType string

const (
	NetExplosiveClassificationTypeNET_EXPLOSIVE_CONTENT NetExplosiveClassificationType = "NET_EXPLOSIVE_CONTENT"

	NetExplosiveClassificationTypeNET_EXPLOSIVE_MASS NetExplosiveClassificationType = "NET_EXPLOSIVE_MASS"

	NetExplosiveClassificationTypeNET_EXPLOSIVE_QUANTITY NetExplosiveClassificationType = "NET_EXPLOSIVE_QUANTITY"

	NetExplosiveClassificationTypeNET_EXPLOSIVE_WEIGHT NetExplosiveClassificationType = "NET_EXPLOSIVE_WEIGHT"
)