package SimpleType



type ServiceType string

const (
	ServiceTypeEUROPE_FIRST_INTERNATIONAL_PRIORITY ServiceType = "EUROPE_FIRST_INTERNATIONAL_PRIORITY"

	ServiceTypeFEDEX_1_DAY_FREIGHT ServiceType = "FEDEX_1_DAY_FREIGHT"

	ServiceTypeFEDEX_2_DAY ServiceType = "FEDEX_2_DAY"

	ServiceTypeFEDEX_2_DAY_AM ServiceType = "FEDEX_2_DAY_AM"

	ServiceTypeFEDEX_2_DAY_FREIGHT ServiceType = "FEDEX_2_DAY_FREIGHT"

	ServiceTypeFEDEX_3_DAY_FREIGHT ServiceType = "FEDEX_3_DAY_FREIGHT"

	ServiceTypeFEDEX_CARGO_AIRPORT_TO_AIRPORT ServiceType = "FEDEX_CARGO_AIRPORT_TO_AIRPORT"

	ServiceTypeFEDEX_CARGO_FREIGHT_FORWARDING ServiceType = "FEDEX_CARGO_FREIGHT_FORWARDING"

	ServiceTypeFEDEX_CARGO_INTERNATIONAL_EXPRESS_FREIGHT ServiceType = "FEDEX_CARGO_INTERNATIONAL_EXPRESS_FREIGHT"

	ServiceTypeFEDEX_CARGO_INTERNATIONAL_PREMIUM ServiceType = "FEDEX_CARGO_INTERNATIONAL_PREMIUM"

	ServiceTypeFEDEX_CARGO_MAIL ServiceType = "FEDEX_CARGO_MAIL"

	ServiceTypeFEDEX_CARGO_REGISTERED_MAIL ServiceType = "FEDEX_CARGO_REGISTERED_MAIL"

	ServiceTypeFEDEX_CARGO_SURFACE_MAIL ServiceType = "FEDEX_CARGO_SURFACE_MAIL"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE ServiceType = "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_EXCLUSIVE_USE ServiceType = "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_EXCLUSIVE_USE"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_NETWORK ServiceType = "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_NETWORK"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_CHARTER_AIR ServiceType = "FEDEX_CUSTOM_CRITICAL_CHARTER_AIR"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_POINT_TO_POINT ServiceType = "FEDEX_CUSTOM_CRITICAL_POINT_TO_POINT"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE ServiceType = "FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE_EXCLUSIVE_USE ServiceType = "FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE_EXCLUSIVE_USE"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_AIR ServiceType = "FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_AIR"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_VALIDATED_AIR ServiceType = "FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_VALIDATED_AIR"

	ServiceTypeFEDEX_CUSTOM_CRITICAL_WHITE_GLOVE_SERVICES ServiceType = "FEDEX_CUSTOM_CRITICAL_WHITE_GLOVE_SERVICES"

	ServiceTypeFEDEX_DISTANCE_DEFERRED ServiceType = "FEDEX_DISTANCE_DEFERRED"

	ServiceTypeFEDEX_EXPRESS_SAVER ServiceType = "FEDEX_EXPRESS_SAVER"

	ServiceTypeFEDEX_FIRST_FREIGHT ServiceType = "FEDEX_FIRST_FREIGHT"

	ServiceTypeFEDEX_FREIGHT_ECONOMY ServiceType = "FEDEX_FREIGHT_ECONOMY"

	ServiceTypeFEDEX_FREIGHT_PRIORITY ServiceType = "FEDEX_FREIGHT_PRIORITY"

	ServiceTypeFEDEX_GROUND ServiceType = "FEDEX_GROUND"

	ServiceTypeFEDEX_NEXT_DAY_AFTERNOON ServiceType = "FEDEX_NEXT_DAY_AFTERNOON"

	ServiceTypeFEDEX_NEXT_DAY_EARLY_MORNING ServiceType = "FEDEX_NEXT_DAY_EARLY_MORNING"

	ServiceTypeFEDEX_NEXT_DAY_END_OF_DAY ServiceType = "FEDEX_NEXT_DAY_END_OF_DAY"

	ServiceTypeFEDEX_NEXT_DAY_FREIGHT ServiceType = "FEDEX_NEXT_DAY_FREIGHT"

	ServiceTypeFEDEX_NEXT_DAY_MID_MORNING ServiceType = "FEDEX_NEXT_DAY_MID_MORNING"

	ServiceTypeFIRST_OVERNIGHT ServiceType = "FIRST_OVERNIGHT"

	ServiceTypeGROUND_HOME_DELIVERY ServiceType = "GROUND_HOME_DELIVERY"

	ServiceTypeINTERNATIONAL_DISTRIBUTION_FREIGHT ServiceType = "INTERNATIONAL_DISTRIBUTION_FREIGHT"

	ServiceTypeINTERNATIONAL_ECONOMY ServiceType = "INTERNATIONAL_ECONOMY"

	ServiceTypeINTERNATIONAL_ECONOMY_DISTRIBUTION ServiceType = "INTERNATIONAL_ECONOMY_DISTRIBUTION"

	ServiceTypeINTERNATIONAL_ECONOMY_FREIGHT ServiceType = "INTERNATIONAL_ECONOMY_FREIGHT"

	ServiceTypeINTERNATIONAL_FIRST ServiceType = "INTERNATIONAL_FIRST"

	ServiceTypeINTERNATIONAL_PRIORITY ServiceType = "INTERNATIONAL_PRIORITY"

	ServiceTypeINTERNATIONAL_PRIORITY_DISTRIBUTION ServiceType = "INTERNATIONAL_PRIORITY_DISTRIBUTION"

	ServiceTypeINTERNATIONAL_PRIORITY_EXPRESS ServiceType = "INTERNATIONAL_PRIORITY_EXPRESS"

	ServiceTypeINTERNATIONAL_PRIORITY_FREIGHT ServiceType = "INTERNATIONAL_PRIORITY_FREIGHT"

	ServiceTypePRIORITY_OVERNIGHT ServiceType = "PRIORITY_OVERNIGHT"

	ServiceTypeSAME_DAY ServiceType = "SAME_DAY"

	ServiceTypeSAME_DAY_CITY ServiceType = "SAME_DAY_CITY"

	ServiceTypeSMART_POST ServiceType = "SMART_POST"

	ServiceTypeSTANDARD_OVERNIGHT ServiceType = "STANDARD_OVERNIGHT"

	ServiceTypeTRANSBORDER_DISTRIBUTION_CONSOLIDATION ServiceType = "TRANSBORDER_DISTRIBUTION_CONSOLIDATION"
)
