package SimpleType

type ShipmentDryIceProcessingOptionType string

const (
	ShipmentDryIceProcessingOptionTypeSHIPMENT_LEVEL_DRY_ICE_ONLY ShipmentDryIceProcessingOptionType = "SHIPMENT_LEVEL_DRY_ICE_ONLY"
)
