package SimpleType

// Identifies the type of artifact created.
type ArtifactType string

const (
	ArtifactTypeAUXILIARY_LABEL ArtifactType = "AUXILIARY_LABEL"

	ArtifactTypeCERTIFICATE_OF_ORIGIN ArtifactType = "CERTIFICATE_OF_ORIGIN"

	ArtifactTypeCOD_RETURN_LABEL ArtifactType = "COD_RETURN_LABEL"

	ArtifactTypeCOMMERCIAL_INVOICE ArtifactType = "COMMERCIAL_INVOICE"

	ArtifactTypeCOMMODITIES_BY_TRACKING_NUMBER_REPORT ArtifactType = "COMMODITIES_BY_TRACKING_NUMBER_REPORT"

	ArtifactTypeCONDENSED_CRN_REPORT ArtifactType = "CONDENSED_CRN_REPORT"

	ArtifactTypeCONSOLIDATED_COMMERCIAL_INVOICE ArtifactType = "CONSOLIDATED_COMMERCIAL_INVOICE"

	ArtifactTypeCONSOLIDATED_CUSTOMS_LINEHAUL_REPORT ArtifactType = "CONSOLIDATED_CUSTOMS_LINEHAUL_REPORT"

	ArtifactTypeCONSOLIDATED_SOLD_TO_SUMMARY_REPORT ArtifactType = "CONSOLIDATED_SOLD_TO_SUMMARY_REPORT"

	ArtifactTypeCRN_REPORT ArtifactType = "CRN_REPORT"

	ArtifactTypeCUSTOMS_PACKING_LIST ArtifactType = "CUSTOMS_PACKING_LIST"

	ArtifactTypeCUSTOM_CONSOLIDATION_DOCUMENT ArtifactType = "CUSTOM_CONSOLIDATION_DOCUMENT"

	ArtifactTypeCUSTOM_PACKAGE_DOCUMENT ArtifactType = "CUSTOM_PACKAGE_DOCUMENT"

	ArtifactTypeCUSTOM_SHIPMENT_DOCUMENT ArtifactType = "CUSTOM_SHIPMENT_DOCUMENT"

	ArtifactTypeDANGEROUS_GOODS_SHIPPERS_DECLARATION ArtifactType = "DANGEROUS_GOODS_SHIPPERS_DECLARATION"

	ArtifactTypeDELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_LABEL ArtifactType = "DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_LABEL"

	ArtifactTypeFREIGHT_ADDRESS_LABEL ArtifactType = "FREIGHT_ADDRESS_LABEL"

	ArtifactTypeGENERAL_AGENCY_AGREEMENT ArtifactType = "GENERAL_AGENCY_AGREEMENT"

	ArtifactTypeLOW_CUSTOMS_VALUE_EXCEPTION_PARTY_REPORT ArtifactType = "LOW_CUSTOMS_VALUE_EXCEPTION_PARTY_REPORT"

	ArtifactTypeNAFTA_CERTIFICATE_OF_ORIGIN ArtifactType = "NAFTA_CERTIFICATE_OF_ORIGIN"

	ArtifactTypeOP_900 ArtifactType = "OP_900"

	ArtifactTypeOUTBOUND_LABEL ArtifactType = "OUTBOUND_LABEL"

	ArtifactTypePRO_FORMA_INVOICE ArtifactType = "PRO_FORMA_INVOICE"

	ArtifactTypeRETURN_INSTRUCTIONS ArtifactType = "RETURN_INSTRUCTIONS"

	ArtifactTypeSERVICE_REPLY ArtifactType = "SERVICE_REPLY"

	ArtifactTypeSERVICE_REQUEST ArtifactType = "SERVICE_REQUEST"

	ArtifactTypeSTANDARD_BROKER_CLEARANCE_PARTY_REPORT ArtifactType = "STANDARD_BROKER_CLEARANCE_PARTY_REPORT"

	ArtifactTypeTERMS_AND_CONDITIONS ArtifactType = "TERMS_AND_CONDITIONS"
)
