package SimpleType

type AssociatedShipmentType string

const (
	AssociatedShipmentTypeCOD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN AssociatedShipmentType = "COD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN"

	AssociatedShipmentTypeCOD_RETURN AssociatedShipmentType = "COD_RETURN"

	AssociatedShipmentTypeDELIVERY_ON_INVOICE_ACCEPTANCE_RETURN AssociatedShipmentType = "DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN"
)
