package SimpleType

type TrackingDateOrTimestampType string

const (
	TrackingDateOrTimestampTypeACTUAL_DELIVERY TrackingDateOrTimestampType = "ACTUAL_DELIVERY"

	TrackingDateOrTimestampTypeACTUAL_PICKUP TrackingDateOrTimestampType = "ACTUAL_PICKUP"

	TrackingDateOrTimestampTypeACTUAL_TENDER TrackingDateOrTimestampType = "ACTUAL_TENDER"

	TrackingDateOrTimestampTypeANTICIPATED_TENDER TrackingDateOrTimestampType = "ANTICIPATED_TENDER"

	TrackingDateOrTimestampTypeAPPOINTMENT_DELIVERY TrackingDateOrTimestampType = "APPOINTMENT_DELIVERY"

	TrackingDateOrTimestampTypeESTIMATED_DELIVERY TrackingDateOrTimestampType = "ESTIMATED_DELIVERY"

	TrackingDateOrTimestampTypeESTIMATED_PICKUP TrackingDateOrTimestampType = "ESTIMATED_PICKUP"

	TrackingDateOrTimestampTypeESTIMATED_RETURN_TO_STATION TrackingDateOrTimestampType = "ESTIMATED_RETURN_TO_STATION"

	TrackingDateOrTimestampTypeSHIP TrackingDateOrTimestampType = "SHIP"
)
